---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: test
    encrypted_data_bag_secret_key_path: "test/integration/test/test_encrypted_data_bag_secret"
    run_list:
      - recipe[bcs_certificate::test]
